{{ if .Values.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "gel.fullname" . }}-tls-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gel.labels" . | nindent 4 }}
spec:
  secretName: {{ default (printf "%s-tls-cert" (include "gel.fullname" .)) .Values.tls.secretName }}
  duration: {{ .Values.tls.duration }}
  renewBefore: {{ .Values.tls.renewBefore }}
  privateKey:
    algorithm: {{ .Values.tls.privateKey.algorithm }}
    size: {{ .Values.tls.privateKey.size }}
  subject:
    organizations:
      {{- range .Values.tls.subject.organizations }}
      - {{ . }}
      {{- end }}
  commonName: {{ .Values.tls.commonName }}
  dnsNames:
    - '*.{{ include "gel.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local'
    - '*.{{ include "gel.fullname" . }}.{{ .Release.Namespace }}.svc.local'
    - '*.{{ include "gel.fullname" . }}.{{ .Release.Namespace }}.svc'
    - '*.{{ include "gel.fullname" . }}.{{ .Release.Namespace }}'
    - '{{ include "gel.fullname" . }}'
    - '{{ .Values.tls.commonName }}'
    {{- range .Values.tls.additionalDnsNames }}
    - {{ . }}
    {{- end }}
  issuerRef:
    name: {{ .Values.tls.issuerName | default "cluster-issuer" }}
    kind: {{ .Values.tls.issuerKind | default "ClusterIssuer" }}
    group: cert-manager.io
{{- end }}
