{{- if and (not .Values.postgresdb.postgresdbInternal.enabled) (not .Values.postgresdb.postgresdbExternal.enabled) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gel.fullname" . }}-data
  labels:
    {{- include "gel.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.gel.storage.storageClassName | default "standard" }}
  resources:
    requests:
      storage: {{ .Values.gel.storage.size }}
{{- end }}
