apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gel.fullname" . }}-auth
  labels:
    {{- include "gel.labels" . | nindent 4 }}
type: Opaque
data:
  GEL_SERVER_USER: {{ .Values.gel.auth.username | b64enc }}
  GEL_SERVER_PASSWORD: {{ .Values.gel.auth.password | b64enc }}
