apiVersion: v1
kind: Service
metadata:
  name: {{ include "gel.fullname" . }}
  labels:
    {{- include "gel.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "gel.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      name: {{ .Values.service.name | quote }}
      targetPort: {{ .Values.service.port }}
