{{- if .Values.serviceAccount.create | default false }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gel.serviceAccountName" . }}
  labels:
    {{- include "gel.labels" . | nindent 4 }}
{{- end }}
