{{- if and (not .Values.postgresdb.postgresdbInternal.enabled) (not .Values.postgresdb.postgresdbExternal.enabled) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "edgedb.fullname" . }}-data
  labels:
    {{- include "edgedb.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.edgedb.storage.storageClassName | default "standard" }}
  resources:
    requests:
      storage: {{ .Values.edgedb.storage.size }}
{{- end }}
