apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edgedb.fullname" . }}-auth
  labels:
    {{- include "edgedb.labels" . | nindent 4 }}
type: Opaque
stringData:
  EDGEDB_SERVER_USER: {{ .Values.edgedb.auth.username | b64enc }}
  EDGEDB_SERVER_PASSWORD: {{ .Values.edgedb.auth.password | b64enc }}
