{{- if .Values.serviceAccount.create | default false }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "edgedb.serviceAccountName" . }}
  labels:
    {{- include "edgedb.labels" . | nindent 4 }}
{{- end }}
