apiVersion: v1
kind: Service
metadata:
  name: {{ include "edgedb.fullname" . }}
  labels:
    {{- include "edgedb.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "edgedb.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 5656
      name: {{ .Values.service.name | quote }}
      targetPort: 5656 
